### PR TITLE
Move inline JS + CSS to dedicated files + remove unused pdf_redirect.…

### LINKED ISSUE #39: Remove inline javascript to comply with some CSP
Tested with https://download.kiwix.org/zim/videos/khan-academy-videos_ar_khws-l-dd_2021-12.zim

Every page has the following webp-polyfill related inline code :

`<script>$(document).ready(function() { trigger_webp_polyfill(); });</script>`

It is blocked when some Content Security Policies ban inline javascript. It is in particular the case in kiwix-js browser extensions.

Moving this line of code in a javascript file should be enough to fix it, in this case.

### PR DESCRIPTION
**Pull request by benoit74**
# Rationale

Fix #39 

# Changes

- inline javascript of `document.html`, `perseus_exercice.html`, `epub_embed.html` have been moved to dedicated file + cleaned-up from unused variables / code blocks
- inline CSS of huge `<style>` block in `epub_embed.html` has been moved to dedicated file
- `pdf_redirect.html` has been removed because it was not used at all in the code base, and contained javascript which was templated so complex to migrate to dedicated file (would probably have needed to adapt the generation, but without the code generating, it was ... complex ^^)
- add `--node-ids` CLI parameter to process only few nodes (useful for debugging) with sample command in the README
- fixed issue with ePub rendering which was outside the iframe

### CODE REVIEW

**Comment by benoit74** [comment]
Still a draft for now, I'm performing a scrapper run to confirm it works as intended + checking codefactor result.

**Review by rgaudin — APPROVED** [review]
Changed status of PR to review it. Looks good to me ✅

On `pdf_redirect.html`, I think it was a first iteration to _support_ PDF by providing access to them (via an HTML redirect).
Eventually, we added PDF.js because of Orange's deployment that lacks a PDF reader (and browser doesn't include it).
I'm not convinced bundled PDF.js is perfect for all cases but we've not used kolibri enough yet. Maybe it will come back as an option at some point. It's fine to remove it now.

@benoit74 please make sure those embed content like epub and pdf work fine with [kiwix-serve nightly](http://download.kiwix.org/nightly/kiwix-tools_macos-x86_64.tar.gz) (on both Firefox and Chrome) as we've had difficulties with iframe sandboxing recently and I'm not sure we've checked kolibri ZIM files.

**Comment by rgaudin** [comment]
kolibri was originaly developed for libretexts. See https://farm.openzim.org/recipes/libretexts-engineering

**Comment by benoit74** [comment]
There is no (more ?) epub in libretexts-engineering ... any other hint ?

**Comment by benoit74** [comment]
epub are indeed broken, but it looks like it has nothing to do with this change or the ones you did elsewhere. 

See below how the scrollbar is at the top but the top of the page is already cropped, and we already see the "bottom" of the epub page.
broken_epub

I have a fix almost ready, I'm currently testing it in a real condition (I hacked a bit to isolate the issue :))

Notice that I also added a commit which introduce a new parameter to process only few nodes.

**Comment by benoit74** [comment]
@rgaudin 

I added those two new changes:
```
- add `--node-ids` CLI parameter to process only few nodes (useful for debugging) with sample command in the README
- fixed issue with ePub rendering which was outside the iframe
```

I had to rewrite all commits because the first one contained messy `console.log` debug command in JS file, sorry about that.

Tested with Kiwix JS, pwa.kiwix.org and nightly kiwixserve on MacOS, each time with Firefox and Chrome, looks good so far.

Please review and merge (I do not have sufficient rights, or give them to me ^^)

Btw, I found why I did not achieved to understand the case mentioned in the original issue, it's an archive created by `youtube` offliner 🙄 🤣

**Review by rgaudin — APPROVED** [review]
👍  @benoit74 please push the minor change we did together (move up the option in entrypoint) then merge.

**Pull request merged**
