### PR TITLE
fix issue 71

### PR DESCRIPTION
**Pull request by githyuvi**
closes issue #71 

Tested with African StoryBook Library Zim

https://github.com/openzim/kolibri/assets/96630446/7d574be7-6f97-4846-8442-63ff2f846b0a

### CODE REVIEW

**Comment by githyuvi** [comment]
commit 2d8e689 adds the following functionality. 
left arrow is disabled for slide index = 0 and right arrow is disabled for slide index = last slide index.

**Review by benoit74 — APPROVED** [review]
Very good, thank you. I will merge it and update issue.

**Comment by benoit74** [comment]
I fucked-up the rebase, and the PR, I've just reopened it, sorry

**Comment by benoit74** [comment]
@githyuvi one small remark: you should not commit to your `new_ui` branch but checkout a specific new branch for each issue (or set of issues) you wanna work on, and give a "meaningful" name to this branch

**Comment by githyuvi** [comment]
@benoit74 sure👍

**Pull request closed without merging**
